import "dotenv/config";
import OpenAI from "openai";
import { readFileSync, writeFileSync } from "fs";
import { execSync } from "child_process";

const client = new OpenAI();

/**
 * Scenario: We have an existing codebase with tests. We want to add a new feature by prompting the LLM to modify the
 * code. We want to make sure we don't break anything. We also want to generate a changelog entry from the diff.
*/
const code = readFileSync("products.ts", "utf-8");

// LLM Call 1 - Generate new code
// Just a prompt example, can be anything!
// e.g. passed from user input, or generated by another agent, etc.
// important is the workflow: read -> prompt -> write -> test -> rollback if failed
const response = await client.responses.create({
  model: "gpt-5.2",
  input: `Add a new exported function called "getCheapest" that takes the same arguments but returns the cheapest products instead. Keep the existing code unchanged. Return ONLY the full file code, no markdown, no explanation.\n\n${code}`,
});

const newCode = response.output_text;

if (!newCode.includes("getCheapest")) {
  console.log("❌ Gate 1 failed: new function not found");
  process.exit(1);
}
console.log("✅ Gate 1: New function found\n");

// Step 3: Write the updated code
// important: we write the code, not the LLM.
// this allows for more control.
writeFileSync("products.ts", newCode);

// Gate 2: Run the existing tests
try {
  const output = execSync("npx tsx tests.ts", { encoding: "utf-8" });
  console.log("✅ Gate 2:", output.trim());
} catch (error: any) {
  console.log("❌ Gate 2 failed: tests broke - rolling back");
  writeFileSync("products.ts", code);
  console.log(error.stdout);
  process.exit(1);
}

// Step 4: LLM Call 2 - Generate a changelog entry from the diff
const changelog = await client.responses.create({
  model: "gpt-5.2",
  input: `Here is the original code:\n\n${code}\n\nHere is the updated code:\n\n${newCode}\n\nWrite a short one-line changelog entry describing what changed. Just the line, nothing else.`,
});

console.log("\n=== Changelog ===");
console.log(changelog.output_text);

writeFileSync("CHANGELOG.md", `- ${changelog.output_text}\n`, { flag: "a", encoding: "utf-8" });